icons_format = "{icon}"

[theme]
theme = "nord-dark"
[theme.overrides]
alternating_tint_bg = "#2e3440"
alternating_tint_fg = "#d8dee9"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"

# ddcutil brightness
[[block]]
block = "custom"
command = "ddcutil getvcp 10 | awk -F '=' '{print $2}' | awk -F ',' '{print $1}'"
format = " \uf185 $text.pango-str()% "
watch_files = ["~/.config/i3status-rust/brightness"]

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
# cmd = "volctl" #"pavucontrol"

[[block]]
block = "music"


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
