
[font]
size = 14.4

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Fira Code Nerd Font"
style = "Medium"

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"


[font.offset]
x = 0
y = 0

[env]
TERM = "xterm-256color"

[general]
import = [
    # uncomment the flavour you want below:
    # "~/.config/alacritty/catppuccin-latte.toml",
    # "~/.config/alacritty/catppuccin-frappe.toml",
    "~/.config/alacritty/catppuccin-macchiato.toml",
    # "~/.config/alacritty/catppuccin-mocha.toml",
]
