version = 3
final_space = true

[palette]
  blue = '#8AADF4'
  flamingo = '#F2CDCD'
  green = '#A6E3A1'
  lavender = '#B7BDF8'
  os = '#ACB0BE'
  peach = '#FAB387'
  pink = '#F5BDE6'
  red = '#F38BA8'
  rosewater = '#F5E0DC'
  text = '#494D64'
  wight = '#FFFFFF'
  yellow = '#EED49F'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = '╭─'
    trailing_diamond = ''
    template = ' {{ .Icon }} '
    foreground = 'p:wight'
    background = 'p:text'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ .Path }} '
    foreground = 'p:text'
    background = 'p:blue'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      edge_format = '<b>%s</b>'
      folder_icon = '  '
      folder_separator_icon = '/'
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ .HEAD }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }} '
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:green'
    type = 'git'
    style = 'diamond'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  filler = '<p:text,#24273A>─</>'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ if eq .Code 0 }}✔{{ else }} {{ reason .Code }}{{ end }} '
    foreground = 'p:green'
    background = 'p:text'
    type = 'status'
    style = 'diamond'
    foreground_templates = ['{{ if .Error }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ end }} '
    foreground = 'p:text'
    background = 'p:blue'
    type = 'python'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if .SSHSession }} {{ .UserName }}@{{ .HostName }} {{ end }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'session'
    style = 'accordion'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    foreground = 'p:flamingo'
    powerline_symbol = ''
    background = 'p:text'
    type = 'time'
    style = 'diamond'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─'
    foreground = 'p:text'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
